language: python
python:
  - "3.9"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - docker
install:
  - pipenv install --system
before_script:
  - pip install docker-compose
  - export SECRET_KEY=test
  - export DB_NAME=filmosaurus
  - export DB_USER=postgres
  - export DB_PASSWORD=postgres
  - export DB_HOST=db
  - export DB_PORT=5432
  - export CACHE_LOCATION=cache
script:
  - docker-compose run web sh -c "python manage.py test"