language: python
python:
  - "3.9"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - docker
install:
  - pipenv install --system
before_script: pip install docker-compose
script:
  - export SECRET_KEY=echo "$SECRET_KEY"
  - export DB_NAME=echo "$DB_NAME"
  - export DB_USER=echo "$DB_USER"
  - export DB_PASSWORD=echo "$DB_PASSWORD"
  - export DB_HOST=echo "$DB_HOST"
  - export DB_PORT=echo "$DB_PORT"
  - export CACHE_LOCATION=echo "$CACHE_LOCATION"
  - docker-compose run web sh -c "python manage.py test"