language: python
python:
  - "3.9"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - redis
  - docker
install:
  - pipenv install --system
before_script:
  - pip install docker-compose
  - cd core/
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DB_NAME=$DB_NAME >> .env
  - echo DB_USER=$DB_USER >> .env
  - echo DB_PASSWORD=$DB_PASSWORD >> .env
  - echo DB_HOST=$DB_HOST >> .env
  - echo DB_PORT=$DB_PORT >> .env
  - echo CACHE_LOCATION=$CACHE_LOCATION >> .env
  - EMAIL_HOST=$EMAIL_HOST >> .env
  - EMAIL_HOST_USER=$EMAIL_HOST_USER >> .env
  - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD >> .env
  - EMAIL_PORT=$EMAIL_PORT >> .env
  - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL >> .env
script:
  - docker-compose run web sh -c "flake8 . && coverage run --source="." manage.py test && coverage report -m"