language: python
python:
  - "3.9"
env:
  - DJANGO_SETTINGS_MODULE="core.settings"
services:
  - postgresql
  - redis-server
install:
  - pipenv install --system
before_script:
   - psql -c 'create database filmosaurus;'
script:
  - export SECRET_KEY='test'
  - export DB_PASSWORD='test'
  - export DB_USER='postgres'
  - export DB_NAME='filmosaurus'
  - export DB_PORT=5432
  - export EMAIL_HOST=smtp.test.mc
  - export EMAIL_USER=test@test.mc
  - export EMAIL_PASSWORD=test1235
  - export EMAIL_PORT=587
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test