version: '3.3'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
      - cache
    links:
      - db:db
    networks:
      - djangonetwork
  db:
    image: postgres:12
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - djangonetwork
    ports:
       - '5432'
  cache:
    image: redis
    volumes:
      - redis_data:/var/lib/redis/data/
    environment: 
      - "ALLOW_EMPTY_PASSWORD=yes"
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
volumes:
  postgres_data:
  redis_data: