# Generated by Django 3.2.7 on 2021-09-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='casts',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='country',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='directors',
        ),
    ]
