# Generated by Django 3.2.7 on 2021-10-03 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210930_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='saved_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='viewed_date',
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
