# Generated by Django 3.2.7 on 2021-10-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20211003_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='saved_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='viewed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
