# Generated by Django 3.2.7 on 2021-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20211003_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='viewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
